//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionForm
    {
        public int AdmisionID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string FrequencyAdmission { get; set; }
        public string WhenStudentAdmit { get; set; }
        public string Instrument { get; set; }
        public string MiniRequirement { get; set; }
        public Nullable<bool> Merit { get; set; }
        public string MeritCompiled { get; set; }
        public string policies { get; set; }
        public Nullable<int> InductionYearsAdmissionID { get; set; }
    
        public virtual InductionYearsAdmission InductionYearsAdmission { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Program Program { get; set; }
    }
}
