//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnus
    {
        public int AlumniID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public string FacilityInternship { get; set; }
        public string ContactAlumni { get; set; }
        public string CommunicateGraduates { get; set; }
        public string AlumniAssociation { get; set; }
        public int ProgramID { get; set; }
        public Nullable<int> YearlyPassoutID { get; set; }
        public string GraduateIndustryPath { get; set; }
        public string GraduateAcademicsPath { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual Program Program { get; set; }
        public virtual YearlyPassout YearlyPassout { get; set; }
    }
}
