//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentReport()
        {
            this.StudentReports = new HashSet<StudentReport>();
        }
    
        public int AssignReportID { get; set; }
        public Nullable<int> CLOnumber { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<int> SCRID { get; set; }
        public Nullable<int> RubricsID { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Rubric Rubric { get; set; }
        public virtual StudentCourseReg StudentCourseReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReport> StudentReports { get; set; }
    }
}
