//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssignmentReports = new HashSet<AssignmentReport>();
        }
    
        public int AssignmentID { get; set; }
        public Nullable<int> AssignNumber { get; set; }
        public string AssignName { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> DedlineDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> InstructorID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Program Program { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentReport> AssignmentReports { get; set; }
    }
}
