//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableRoom
    {
        public int AvailableRoomID { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public string RoomLocation { get; set; }
        public Nullable<bool> multimedia { get; set; }
        public Nullable<bool> airConditioned { get; set; }
        public Nullable<bool> wifi { get; set; }
        public Nullable<bool> sound { get; set; }
        public Nullable<bool> advancedEquipment { get; set; }
        public Nullable<bool> lights { get; set; }
        public Nullable<bool> fans { get; set; }
        public Nullable<bool> whiteboard { get; set; }
        public Nullable<bool> projector { get; set; }
    
        public virtual RoomType RoomType { get; set; }
    }
}
