//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputingBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComputingBudget()
        {
            this.HecAdministrations = new HashSet<HecAdministration>();
            this.HecAdministrations1 = new HashSet<HecAdministration>();
        }
    
        public int ComputingBudgetID { get; set; }
        public string TotalCompLab { get; set; }
        public string AvgCompLab { get; set; }
        public string AvgLifetimePC { get; set; }
        public string LabContact { get; set; }
        public string DLDlab { get; set; }
        public string FYPLab { get; set; }
        public Nullable<int> ComputerRatioID { get; set; }
        public Nullable<int> LevelNetworkingID { get; set; }
        public Nullable<int> LabAvailabilityID { get; set; }
        public Nullable<int> DepComputingBudgetID { get; set; }
        public Nullable<int> CYearlyBudgetID { get; set; }
    
        public virtual ComputerRatio ComputerRatio { get; set; }
        public virtual CYearlyBudget CYearlyBudget { get; set; }
        public virtual DepComputingBudget DepComputingBudget { get; set; }
        public virtual LabAvailability LabAvailability { get; set; }
        public virtual LevelNetworking LevelNetworking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations1 { get; set; }
    }
}
