//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDescription
    {
        public int CourseDescriptionID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string URL { get; set; }
        public string Textbook { get; set; }
        public string CourseGoals { get; set; }
        public string ProjectCourse { get; set; }
        public string ProgrammingAssignment { get; set; }
        public string Reference { get; set; }
        public string AssessmentWeights { get; set; }
        public string TimeSpentTheory { get; set; }
        public string TimeSpentProblem { get; set; }
        public string TimeSpentSolution { get; set; }
        public string TimeSpentIssues { get; set; }
        public string OWwritten { get; set; }
        public string OWpages { get; set; }
        public string OWpresentation { get; set; }
        public Nullable<int> OWminutes { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> TermID { get; set; }
        public string CatalogNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Duration { get; set; }
        public string EvaluationInstrument { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseCatDescription { get; set; }
        public string topicCover { get; set; }
        public string Application { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Program Program { get; set; }
        public virtual Term Term { get; set; }
    }
}
