//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRI
    {
        public int CRI_ID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string HecComputingCore { get; set; }
        public string HecMajorCore { get; set; }
        public string HecBasedlective { get; set; }
        public string HecCumulative { get; set; }
        public string HecSupportingSci { get; set; }
        public string HecUniversityElective { get; set; }
        public string HecGeneralElective { get; set; }
        public string HecCumulativeCredit { get; set; }
        public string HecTotalCredit { get; set; }
        public string SumComputingCore { get; set; }
        public string SumMajorCore { get; set; }
        public string SumBasedlective { get; set; }
        public string SumCumulative { get; set; }
        public string SumSupportingSci { get; set; }
        public string SumUniversityElective { get; set; }
        public string SumGeneralElective { get; set; }
        public string SumCumulativeCredit { get; set; }
        public string SumTotalCredit { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Program Program { get; set; }
    }
}
