//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECourseFoder
    {
        public int ECourseFolderID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string FolderName { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Program Program { get; set; }
        public virtual Status Status { get; set; }
        public virtual Term Term { get; set; }
    }
}
