//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyCours
    {
        public int FacultyCoursesID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TermID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Term Term { get; set; }
    }
}
