//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIF
    {
        public int FIFID { get; set; }
        public Nullable<int> InsructorID { get; set; }
        public string AcademicDegree { get; set; }
        public string DegreeAwarding { get; set; }
        public string Specialization { get; set; }
        public string ExpHigherEdu { get; set; }
        public string ExpIndustry { get; set; }
        public string PubJnlinternational { get; set; }
        public string PubJnlLocal { get; set; }
        public string PubConinternational { get; set; }
        public string PubConLocal { get; set; }
        public string PubBook { get; set; }
        public string PubBookChap { get; set; }
        public string Patents { get; set; }
        public string TechReports { get; set; }
    
        public virtual Instructor Instructor { get; set; }
    }
}
