//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financial
    {
        public int FinancialID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ResearchBudgetID { get; set; }
        public Nullable<int> LibraryBudgetID { get; set; }
        public Nullable<int> ComputingBudgetID { get; set; }
        public Nullable<int> DepOfferProgBudgetID { get; set; }
        public Nullable<int> FreeStructureID { get; set; }
        public Nullable<int> SourcesOfIncomeID { get; set; }
        public int ProgramID { get; set; }
        public string TotalAssets { get; set; }
        public string Fund { get; set; }
        public Nullable<int> WholeBudgetID { get; set; }
        public Nullable<int> DepResearchBudgetID { get; set; }
        public Nullable<int> DepComputingBudgetID { get; set; }
    
        public virtual DepComputingBudget DepComputingBudget { get; set; }
        public virtual DepOfferProgBudget DepOfferProgBudget { get; set; }
        public virtual DepResearchBudget DepResearchBudget { get; set; }
        public virtual FreeStructure FreeStructure { get; set; }
        public virtual FreeStructure FreeStructure1 { get; set; }
        public virtual LibraryBudget LibraryBudget { get; set; }
        public virtual LibraryBudget LibraryBudget1 { get; set; }
        public virtual Program Program { get; set; }
        public virtual ResearchBudget ResearchBudget { get; set; }
        public virtual ResearchBudget ResearchBudget1 { get; set; }
        public virtual SourcesOfIncome SourcesOfIncome { get; set; }
        public virtual SourcesOfIncome SourcesOfIncome1 { get; set; }
        public virtual WholeBudget WholeBudget { get; set; }
    }
}
