//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HecAdministration
    {
        public int HecAdminID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public Nullable<int> InstructionalFacilitiesID { get; set; }
        public Nullable<int> OtherFacilitiesID { get; set; }
        public Nullable<int> ComputingBudgetID { get; set; }
        public Nullable<int> LibraryBudgetID { get; set; }
    
        public virtual ComputingBudget ComputingBudget { get; set; }
        public virtual ComputingBudget ComputingBudget1 { get; set; }
        public virtual InstructionalFacility InstructionalFacility { get; set; }
        public virtual LibraryBudget LibraryBudget { get; set; }
        public virtual OtherFacility OtherFacility { get; set; }
        public virtual OtherFacility OtherFacility1 { get; set; }
    }
}
