//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionalFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstructionalFacility()
        {
            this.HecAdministrations = new HashSet<HecAdministration>();
        }
    
        public int InstructionalFacilitiesID { get; set; }
        public Nullable<bool> multimedia { get; set; }
        public Nullable<bool> AC { get; set; }
        public Nullable<bool> wifi { get; set; }
        public Nullable<bool> sound { get; set; }
        public Nullable<bool> advanced { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations { get; set; }
    }
}
