//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelNetworking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LevelNetworking()
        {
            this.ComputingBudgets = new HashSet<ComputingBudget>();
        }
    
        public int LevelNetworkingID { get; set; }
        public Nullable<bool> Cisco { get; set; }
        public Nullable<bool> WAN { get; set; }
        public Nullable<bool> HecDigitalLibrary { get; set; }
        public Nullable<bool> Virtualizaion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputingBudget> ComputingBudgets { get; set; }
    }
}
