//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibraryBudget()
        {
            this.Financials = new HashSet<Financial>();
            this.Financials1 = new HashSet<Financial>();
            this.HecAdministrations = new HashSet<HecAdministration>();
        }
    
        public int LibraryBudgetID { get; set; }
        public string HecLib { get; set; }
        public string LibManagment { get; set; }
        public string IEEEElib { get; set; }
        public Nullable<int> LYearlyBudgetID { get; set; }
        public string TotalBooks { get; set; }
        public string NumberOfTitles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial> Financials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financial> Financials1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations { get; set; }
        public virtual LYearlyBudget LYearlyBudget { get; set; }
    }
}
