//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LYearlyBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LYearlyBudget()
        {
            this.LibraryBudgets = new HashSet<LibraryBudget>();
        }
    
        public int LYearlyBudgetID { get; set; }
        public Nullable<int> YearNumber { get; set; }
        public string ComputingBooksAdded { get; set; }
        public string NumberOfMagazines { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibraryBudget> LibraryBudgets { get; set; }
    }
}
