//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherFacility()
        {
            this.HecAdministrations = new HashSet<HecAdministration>();
            this.HecAdministrations1 = new HashSet<HecAdministration>();
        }
    
        public int OtherFacilitiesID { get; set; }
        public Nullable<bool> Ac { get; set; }
        public Nullable<bool> lights { get; set; }
        public Nullable<bool> fans { get; set; }
        public Nullable<bool> whiteboard { get; set; }
        public Nullable<bool> projector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HecAdministration> HecAdministrations1 { get; set; }
    }
}
