//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMPF
    {
        public int PMPFID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Objective { get; set; }
        public string Reviewed { get; set; }
        public string SummaryProblem { get; set; }
        public string SummaryTech { get; set; }
        public string Assesment { get; set; }
        public string CorrelateIndus { get; set; }
        public string Application { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual Institution Institution1 { get; set; }
        public virtual Program Program { get; set; }
        public virtual Program Program1 { get; set; }
    }
}
