//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectReports = new HashSet<ProjectReport>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProjectNumber { get; set; }
        public Nullable<System.DateTime> PAssignDate { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> InstructorID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Instructor Instructor1 { get; set; }
        public virtual Program Program { get; set; }
        public virtual Program Program1 { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectReport> ProjectReports { get; set; }
    }
}
