//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectReport()
        {
            this.SARlists = new HashSet<SARlist>();
        }
    
        public int ProjectIReportD { get; set; }
        public Nullable<int> SCRID { get; set; }
        public Nullable<int> RubricID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual StudentCourseReg StudentCourseReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SARlist> SARlists { get; set; }
    }
}
