//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QecPortalEntities : DbContext
    {
        public QecPortalEntities()
            : base("name=QecPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionForm> AdmissionForms { get; set; }
        public virtual DbSet<Alumnus> Alumni { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<AssignmentReport> AssignmentReports { get; set; }
        public virtual DbSet<AvailableRoom> AvailableRooms { get; set; }
        public virtual DbSet<ComputerRatio> ComputerRatios { get; set; }
        public virtual DbSet<ComputingBudget> ComputingBudgets { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseDescription> CourseDescriptions { get; set; }
        public virtual DbSet<CourseEvaluation> CourseEvaluations { get; set; }
        public virtual DbSet<CourseOutline> CourseOutlines { get; set; }
        public virtual DbSet<CRI> CRIs { get; set; }
        public virtual DbSet<CYearlyBudget> CYearlyBudgets { get; set; }
        public virtual DbSet<DCYearlyBudget> DCYearlyBudgets { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepComputingBudget> DepComputingBudgets { get; set; }
        public virtual DbSet<DepOfferProgBudget> DepOfferProgBudgets { get; set; }
        public virtual DbSet<DepResearchBudget> DepResearchBudgets { get; set; }
        public virtual DbSet<DOPYearlyBudget> DOPYearlyBudgets { get; set; }
        public virtual DbSet<DRYearlyBudget> DRYearlyBudgets { get; set; }
        public virtual DbSet<ECourseFoder> ECourseFoders { get; set; }
        public virtual DbSet<FacultyCours> FacultyCourses { get; set; }
        public virtual DbSet<FIF> FIFs { get; set; }
        public virtual DbSet<Financial> Financials { get; set; }
        public virtual DbSet<FreeStructure> FreeStructures { get; set; }
        public virtual DbSet<FYearlyBudget> FYearlyBudgets { get; set; }
        public virtual DbSet<HecAdministration> HecAdministrations { get; set; }
        public virtual DbSet<InductionYear> InductionYears { get; set; }
        public virtual DbSet<InductionYearsAdmission> InductionYearsAdmissions { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstructionalFacility> InstructionalFacilities { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<LabAvailability> LabAvailabilities { get; set; }
        public virtual DbSet<LevelNetworking> LevelNetworkings { get; set; }
        public virtual DbSet<LibraryBudget> LibraryBudgets { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<LYearlyBudget> LYearlyBudgets { get; set; }
        public virtual DbSet<OtherFacility> OtherFacilities { get; set; }
        public virtual DbSet<PMPF> PMPFs { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectReport> ProjectReports { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<QuizReport> QuizReports { get; set; }
        public virtual DbSet<RatioYearlyBudget> RatioYearlyBudgets { get; set; }
        public virtual DbSet<ResearchBudget> ResearchBudgets { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<Rubric> Rubrics { get; set; }
        public virtual DbSet<RYearlyBudget> RYearlyBudgets { get; set; }
        public virtual DbSet<SAR> SARs { get; set; }
        public virtual DbSet<SourcesOfIncome> SourcesOfIncomes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentCourseReg> StudentCourseRegs { get; set; }
        public virtual DbSet<StudentEvaluation> StudentEvaluations { get; set; }
        public virtual DbSet<StudentReport> StudentReports { get; set; }
        public virtual DbSet<SYearlyBudget> SYearlyBudgets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<WholeBudget> WholeBudgets { get; set; }
        public virtual DbSet<WholeYearlyBudget> WholeYearlyBudgets { get; set; }
        public virtual DbSet<YearlyPassout> YearlyPassouts { get; set; }
    }
}
