//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizReport()
        {
            this.StudentReports = new HashSet<StudentReport>();
        }
    
        public int QuizReportID { get; set; }
        public Nullable<int> CLOnumber { get; set; }
        public Nullable<int> RubricID { get; set; }
        public Nullable<int> QuizID { get; set; }
        public int SCRID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual StudentCourseReg StudentCourseReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReport> StudentReports { get; set; }
    }
}
