//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReport
    {
        public int StudentReportID { get; set; }
        public Nullable<int> AssignReportID { get; set; }
        public Nullable<int> SCRID { get; set; }
        public Nullable<int> QuizIReportD { get; set; }
        public Nullable<int> ProjectReportID { get; set; }
    
        public virtual AssignmentReport AssignmentReport { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectReport ProjectReport { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual QuizReport QuizReport { get; set; }
        public virtual StudentCourseReg StudentCourseReg { get; set; }
    }
}
