//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQecPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyPassout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YearlyPassout()
        {
            this.Alumni = new HashSet<Alumnus>();
        }
    
        public int YearlyPassoutID { get; set; }
        public Nullable<int> YearNumber { get; set; }
        public Nullable<int> NoOfGraduatedTotal { get; set; }
        public Nullable<int> NoOfUnderGraduatedTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnus> Alumni { get; set; }
    }
}
